In [52]:
# https://www.youtube.com/watch?v=0fSn9WG8MrA
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [208]:
# 3. create a function that converts only the 
# first letter of the names to upercase 

sentence = 'siem and tesfit are friends'


yes siem is in the sentence


In [226]:
mySentence = ['siem', 'and', 'tesfit', 'are', 'frieds']

def capitlizerFunc(mySentence):
    
    myNewSentence = []
    
    for item in mySentence:
    
        if item == 'siem' or item == 'tesfit':
            item = item.capitalize()
            myNewSentence.append(item)
        
#         elif item == 'tesfit':
#             item = item.capitalize()
#             myNewSentence.append(item)
            
        else:
            myNewSentence.append(item)
            
    
    return myNewSentence

result = capitlizerFunc(mySentence)
print(result)


['Siem', 'and', 'Tesfit', 'are', 'frieds']


In [ ]:
variable_1 = ['siem', 'and', 'tesfit', 'are', 'frieds']
if 'siem' in variable_1:
    


# Steps
1. read the csv file by selecting the features that you need !!!
2. do the preprocessing --- meaning make the data ready by checking the null or others...
#do feature engeenering, preprocessing [get catagorical features, fill the NaN, drive(create) new features....]
3. catagorize the features you think need to be catagorized
4. check the years, date, ... in the columns if they need to be modified
5. LabelEncoder the cataforical features
6. Convert them first to numpy then to tensor
7. 

# Questions
1. When do we need to worry about the data type while we are doing the feature engineering....

# dimention is vector or number

In [2]:
df=pd.read_csv('houseprice.csv' , usecols=["SalePrice", "MSSubClass", "MSZoning", "LotFrontage", "LotArea",
                                         "Street", "YearBuilt", "LotShape", "1stFlrSF", "2ndFlrSF"]).dropna()
df.shape

(1201, 10)

In [3]:
df.head(3)

MSSubClass MSZoning  LotFrontage  LotArea Street LotShape  YearBuilt  \
0          60       RL         65.0     8450   Pave      Reg       2003   
1          20       RL         80.0     9600   Pave      Reg       1976   
2          60       RL         68.0    11250   Pave      IR1       2001   

   1stFlrSF  2ndFlrSF  SalePrice  
0       856       854     208500  
1      1262         0     181500  
2       920       866     223500

# Feature Engneering

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1201 entries, 0 to 1459
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   MSSubClass   1201 non-null   int64  
 1   MSZoning     1201 non-null   object 
 2   LotFrontage  1201 non-null   float64
 3   LotArea      1201 non-null   int64  
 4   Street       1201 non-null   object 
 5   LotShape     1201 non-null   object 
 6   YearBuilt    1201 non-null   int64  
 7   1stFlrSF     1201 non-null   int64  
 8   2ndFlrSF     1201 non-null   int64  
 9   SalePrice    1201 non-null   int64  
dtypes: float64(1), int64(6), object(3)
memory usage: 103.2+ KB


# Check the columns which needs catagorical feature

In [5]:
#### from this loop u can know which one is catagorical or not ====> feature with less value is a catagorical..
for col in df.columns:
    print(col, len(df[col].unique()))

MSSubClass 15
MSZoning 5
LotFrontage 110
LotArea 869
Street 2
LotShape 4
YearBuilt 112
1stFlrSF 678
2ndFlrSF 368
SalePrice 597


In [6]:
# Now you can LabelEncode them... thoes with few catagories
from sklearn.preprocessing import LabelEncoder
lbEn = LabelEncoder()

categorical_features = ['MSSubClass', 'MSZoning', 'Street', 'LotShape']
for col in categorical_features:
    df[col] = lbEn.fit_transform(df[col])

df.head()

MSSubClass  MSZoning  LotFrontage  LotArea  Street  LotShape  YearBuilt  \
0           5         3         65.0     8450       1         3       2003   
1           0         3         80.0     9600       1         3       1976   
2           5         3         68.0    11250       1         0       2001   
3           6         3         60.0     9550       1         0       1915   
4           5         3         84.0    14260       1         0       2000   

   1stFlrSF  2ndFlrSF  SalePrice  
0       856       854     208500  
1      1262         0     181500  
2       920       866     223500  
3       961       756     140000  
4      1145      1053     250000

# Modify the years col

In [7]:
import datetime
current_year = datetime.datetime.now().year
current_year

2022

In [10]:
df['Modified_year'] = current_year - df['YearBuilt']
df.head(3)

MSSubClass  MSZoning  LotFrontage  LotArea  Street  LotShape  YearBuilt  \
0           5         3         65.0     8450       1         3       2003   
1           0         3         80.0     9600       1         3       1976   
2           5         3         68.0    11250       1         0       2001   

   1stFlrSF  2ndFlrSF  SalePrice  Modified_year  
0       856       854     208500             19  
1      1262         0     181500             46  
2       920       866     223500             21

In [ ]:
type(df['Street']) ### our deep learing model does NOT accept a pandas.core.series.Series type so convert it to tensor

# Convert all the categorical featuers to Numpy then to Tensor

In [11]:
import numpy as np
cate_featu_numpy = np.stack([df['MSSubClass'], df['MSZoning'], df['Street'], df['LotShape']], 1)
cate_featu_numpy

array([[5, 3, 1, 3],
       [0, 3, 1, 3],
       [5, 3, 1, 0],
       ...,
       [6, 3, 1, 3],
       [0, 3, 1, 3],
       [0, 3, 1, 3]])

In [13]:
import torch
cate_featu_tensor = torch.tensor(cate_featu_numpy, dtype=torch.int64)
cate_featu_tensor

tensor([[5, 3, 1, 3],
        [0, 3, 1, 3],
        [5, 3, 1, 0],
        ...,
        [6, 3, 1, 3],
        [0, 3, 1, 3],
        [0, 3, 1, 3]])

# Convert all the Continues featuers to Numpy then to Tensor

In [15]:
conti_features = []

for col in df.columns:
    if col in ['MSSubClass', 'MSZoning', 'Street', 'LotShape', 'SalePrice']:
        pass
    else:
        conti_features.append(col)

print(conti_features)  

['LotFrontage', 'LotArea', 'YearBuilt', '1stFlrSF', '2ndFlrSF', 'Modified_year']


In [16]:
#### convert to numpy then to tensor
conti_featu_numpy = np.stack([df[col] for col in conti_features], axis=1)
conti_featu_tensor=torch.tensor(conti_featu_numpy, dtype=torch.float)
conti_featu_tensor

tensor([[   65.,  8450.,  2003.,   856.,   854.,    19.],
        [   80.,  9600.,  1976.,  1262.,     0.,    46.],
        [   68., 11250.,  2001.,   920.,   866.,    21.],
        ...,
        [   66.,  9042.,  1941.,  1188.,  1152.,    81.],
        [   68.,  9717.,  1950.,  1078.,     0.,    72.],
        [   75.,  9937.,  1965.,  1256.,     0.,    57.]])

# Convert the target also to tensor

In [17]:
#  df['SalePrice'].values  ---- one way of converting to an array
y = np.stack([df['SalePrice']], axis=1)
y = torch.tensor(y)
y

tensor([[208500],
        [181500],
        [223500],
        ...,
        [266500],
        [142125],
        [147500]])

# Check  the shape of all the features

In [18]:
cate_featu_tensor.shape, conti_featu_tensor.shape, y.shape

(torch.Size([1201, 4]), torch.Size([1201, 6]), torch.Size([1201, 1]))

# #################################################################

# Embedding for categorical features

In [22]:
# based on the dim our embedding layer will decided the output e.g. if our input is 15 the output will be 8
# so we need to get the unique values of our categorical features .... see below

In [19]:
categorical_features = ['MSSubClass', 'MSZoning', 'Street', 'LotShape']
cat_dim = [len(df[name].unique()) for name in categorical_features]
cat_dim 

[15, 5, 2, 4]

In [20]:
embedding_dim = [(x, (min(50, (x+1) // 2))) for x in cat_dim]
embedding_dim # this implies -- my output value is half of the input value
# why 50 -- it is a rule

[(15, 8), (5, 3), (2, 1), (4, 2)]

In [23]:
#### In the above if 15 is my input 8 will be the output ...... if 5 then 3 will be output

## So now Once we get the embedding_dim --------> we can create our embedding_layer

In [25]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [26]:
embed_layer = nn.ModuleList([nn.Embedding(inp, out) for inp, out in embedding_dim])
embed_layer

ModuleList(
  (0): Embedding(15, 8)
  (1): Embedding(5, 3)
  (2): Embedding(2, 1)
  (3): Embedding(4, 2)
)

In [135]:
##### Testing.....
r = sum([out for inp, out in embedding_dim])
print('total out put >>>', r)
for inp, out in embedding_dim:
    print(out)

total out put >>> 14
8
3
1
2


In [60]:
#### lets take the first 4 items from the tensor
new_cate_features = cate_featu_tensor[:4] #### for embedding
new_cate_features #### Blow 👇 each vector [5, 3, 1, 3] will represent differently after the embedding... 

tensor([[5, 3, 1, 3],
        [0, 3, 1, 3],
        [5, 3, 1, 0],
        [6, 3, 1, 0]])

In [185]:
new_cate_features[0]

tensor([5, 3, 1, 3])

In [46]:
# not necessary i think
pd.set_option('display.max_row', 50)

# Complicated

In [198]:
#### This line of code is going to show as the output of the embedding_dim from the above
embedding_value = []
for i, e in enumerate(embed_layer):
    print(e)
    embedding_value.append(e(new_cate_features[:, i])) # e([5, 3, 1, 3]) at first iteration..
    
print(embedding_value)


Embedding(15, 8)
Embedding(5, 3)
Embedding(2, 1)
Embedding(4, 2)
[tensor([[-1.3532, -0.4814,  0.7058,  0.1107,  0.6865,  0.2970,  0.2951,  0.2009],
        [ 0.2783,  0.6812,  1.3637,  1.1531,  1.9027, -1.0939, -0.6018, -1.7852],
        [-1.3532, -0.4814,  0.7058,  0.1107,  0.6865,  0.2970,  0.2951,  0.2009],
        [-0.2468,  1.4672, -1.5903,  0.9857,  0.7242, -0.5992, -0.0103, -0.1395]],
       grad_fn=<EmbeddingBackward0>), tensor([[ 0.6473, -0.0180,  0.9882],
        [ 0.6473, -0.0180,  0.9882],
        [ 0.6473, -0.0180,  0.9882],
        [ 0.6473, -0.0180,  0.9882]], grad_fn=<EmbeddingBackward0>), tensor([[-0.3923],
        [-0.3923],
        [-0.3923],
        [-0.3923]], grad_fn=<EmbeddingBackward0>), tensor([[-1.1430,  2.9287],
        [-1.1430,  2.9287],
        [ 0.9440, -1.3560],
        [ 0.9440, -1.3560]], grad_fn=<EmbeddingBackward0>)]


In [54]:
### BUT we need to format it the correct way like the [ new_cate_features ]
### so we use for that the cat method

organized_embedding = torch.cat(embedding_value, 1)
organized_embedding #👍 meaning we are concatinating them in sequence [like [5, 3, 1, 3]]

tensor([[-1.3532, -0.4814,  0.7058,  0.1107,  0.6865,  0.2970,  0.2951,  0.2009,
          0.6473, -0.0180,  0.9882, -0.3923, -1.1430,  2.9287],
        [ 0.2783,  0.6812,  1.3637,  1.1531,  1.9027, -1.0939, -0.6018, -1.7852,
          0.6473, -0.0180,  0.9882, -0.3923, -1.1430,  2.9287],
        [-1.3532, -0.4814,  0.7058,  0.1107,  0.6865,  0.2970,  0.2951,  0.2009,
          0.6473, -0.0180,  0.9882, -0.3923,  0.9440, -1.3560],
        [-0.2468,  1.4672, -1.5903,  0.9857,  0.7242, -0.5992, -0.0103, -0.1395,
          0.6473, -0.0180,  0.9882, -0.3923,  0.9440, -1.3560]],
       grad_fn=<CatBackward0>)

# Dropout 
#### inorder to over come overfitting

In [58]:
# this is one of the regularization method
dropout = nn.Dropout(.4) # 40%
final_embedd = dropout(organized_embedding)
final_embedd ##### we can see it below Some of the values have become zeros

tensor([[-2.2553, -0.8023,  1.1764,  0.1845,  1.1442,  0.0000,  0.4918,  0.3348,
          1.0788, -0.0300,  0.0000, -0.0000, -1.9050,  4.8811],
        [ 0.4639,  1.1354,  2.2729,  0.0000,  3.1712, -1.8231, -0.0000, -0.0000,
          1.0788, -0.0300,  1.6470, -0.0000, -0.0000,  0.0000],
        [-0.0000, -0.8023,  1.1764,  0.0000,  0.0000,  0.0000,  0.0000,  0.3348,
          1.0788, -0.0000,  1.6470, -0.6538,  0.0000, -0.0000],
        [-0.4113,  2.4453, -2.6504,  0.0000,  0.0000, -0.9986, -0.0171, -0.2325,
          1.0788, -0.0300,  0.0000, -0.6538,  0.0000, -0.0000]],
       grad_fn=<MulBackward0>)

# #################################################################

## 🤔 from the embedding till this step will be performed inside our ANN class model

In [67]:
import torch
import torch.nn as nn
import torch.functional as F

In [169]:
class FeedForwardNN(nn.Module):
    def __init__(self, embedding_dim, n_continuse, out_sz, layers, p=0.5):
        super().__init__()
        
        self.embedding_layers = nn.ModuleList([nn.Embedding(inpt, out) for inpt,out in embedding_dim])
        self.embed_dropout = nn.Dropout(p)
        self.batchNorm_continuse = nn.BatchNorm1d(n_continuse)# watch a tutorial
        
        sumNumEmbedingDim = sum((out for inpt,out in embedding_dim))
        n_inpt = sumNumEmbedingDim + n_continuse # >> 14 + 6 = 20 
        
        layerList = []
        for i in layers:
            layerList.append(nn.Linear(n_inpt, i))
            layerList.append(nn.ReLU(inplace=True))
            layerList.append(nn.BatchNorm1d(i))
            layerList.append(nn.Dropout(p))

        layerList.append(nn.Linear(layers[-1], out_sz)) # not clear.....

        self.layers = nn.Sequential(*layerList) # not clear....
        
        
    def forward(self, train_cate, train_conti):
        embeddings  = []
        
        for i, e in enumerate(self.embedding_layers):
            
            embeddings.append(e(train_cate[:, i])) # Not sure if we need this "," 
            
        x = torch.cat(embeddings, 1)
        x = self.embed_dropout(x)

        train_conti = self.batchNorm_continuse(train_conti)
        x = torch.cat([x, train_conti], 1)
        x = self.layers(x)
        return x


In [170]:
print('Len of conti_features >> ', len(conti_features))

torch.manual_seed(100)
model = FeedForwardNN(embedding_dim, len(conti_features), 1, [100, 50], p=0.4)
model


Len of conti_features >>  6


FeedForwardNN(
  (embedding_layers): ModuleList(
    (0): Embedding(15, 8)
    (1): Embedding(5, 3)
    (2): Embedding(2, 1)
    (3): Embedding(4, 2)
  )
  (embed_dropout): Dropout(p=0.4, inplace=False)
  (batchNorm_continuse): BatchNorm1d(6, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (layers): Sequential(
    (0): Linear(in_features=20, out_features=100, bias=True)
    (1): ReLU(inplace=True)
    (2): BatchNorm1d(100, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (3): Dropout(p=0.4, inplace=False)
    (4): Linear(in_features=20, out_features=50, bias=True)
    (5): ReLU(inplace=True)
    (6): BatchNorm1d(50, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (7): Dropout(p=0.4, inplace=False)
    (8): Linear(in_features=50, out_features=1, bias=True)
  )
)

# Loss & Optimzer

In [86]:
loss_func = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

# Train, Test....... split

In [133]:
batch_size =1200 
test_size = int(batch_size * 0.15)

train_cate_featu = cate_featu_tensor[:batch_size - test_size]
test_cate_featu = cate_featu_tensor[batch_size - test_size : batch_size]

train_conti = conti_featu_tensor[:batch_size - test_size]
test_conti = conti_featu_tensor[batch_size - test_size : batch_size]

# y_train = 
# y_test = 


# Question :-
1. Why do we need to split the categorical and continues features Separately ....... ????

In [134]:
len(train_categorical), len(test_categorical), len(train_conti), len(test_conti)

(1020, 180, 1020, 180)

# List Slicing

In [168]:
# Initialize list
Lst = [50, 70, 30, 20, 90, 10, 50]

# Display list
print(Lst[1::5])
print(Lst[1:5])
print(Lst[:3])
print(Lst[3:])



[70, 50]
[70, 30, 20, 90]
[50, 70, 30]
[20, 90, 10, 50]


### The procese of using LabelEncoding is cuz down the road we are going to use the embeding procese

#### My understanding about this project

In [ ]:
# 1. get the data print it by filltering only with the important features...!
# 2. do feature engeenering, preprocessing [get catagorical features, fill the NaN, drive(create) new features....]
# 3. use LabelEncoding cuz you will need to use embedding layers later
# 4. Embedding is not clear

# I have not finished this project


# Questions

In [ ]:
# 1. how do we know which one of our Features need to be LabelEncoded ?
# 2. 