In [1]:
import pandas as pd
import numpy as np

# Standard deviation ----->  SD = square root of sumation( x - x_mean) ** 2 / n

In [ ]:
""" THE PURPOSE OF SD IS -> we do NOT want to have unbalanced distribution of data in our col"""
""" So we need to Normalize or scale it"""

In [18]:
from numpy import asarray
from sklearn.preprocessing import StandardScaler

data = asarray([[401, 10], [220, 1], [200, 3]])


# create dataframe
dfScale = pd.DataFrame(data, columns = ['x1', 'x2'])

def xMean(col):
    return sum(col) / len(col)
    

def x_minuseXmean(col, xMean):
    box = []
    for cell in col:
        box.append((cell - xMean))
    return box


def x_minuseXmeanSqueared(newCol):
    return [cell ** 2 for cell in newCol]
    
dfScale

x1  x2
0  401  10
1  220   1
2  200   3

In [19]:
# StandardDeviation of X1

# find the mean and Standard deviation
x1Mean = xMean(dfScale['x1'])
x1MinuseMean = x_minuseXmean(dfScale['x1'], x1Mean)
x1MinuseMeanSquared = x_minuseXmeanSqueared(x1MinuseMean)


# SD = square root of sumation( x - x_mean) ** 2 / n
standardDeviation_1 = np.sqrt(sum(x1MinuseMeanSquared)  / len(dfScale['x1']) )
print(standardDeviation_1)


#### StandardScaler formula -->.    s = (x1 - xMean) / standardDeviation
s1 = (x1MinuseMean) / standardDeviation_1
print(s1)

90.4077184512227
[ 1.40843432 -0.59360713 -0.81482718]


In [20]:
# StandardDeviation of X2

# find the mean and Standard deviation of x2
x2Mean = xMean(dfScale['x2'])
x2MinuseMean = x_minuseXmean(dfScale['x2'], x2Mean)
x2MinuseMeanSquared = x_minuseXmeanSqueared(x2MinuseMean)


# SD = square root of sumation( x - x_mean) ** 2 / n
standardDeviation_2 = np.sqrt(sum(x2MinuseMeanSquared)  / len(dfScale['x2']) )
print(standardDeviation_2)


#### StandardScaler formula -->.    s = (x2 - xMean) / standardDeviation2
s2 = (x2MinuseMean) / standardDeviation_2
print(s2)

3.858612300930075
[ 1.38218948 -0.95025527 -0.43193421]


In [21]:
# Same as the builtinfunction

print(np.asarray([[s1], [s2]]))

[[[ 1.40843432 -0.59360713 -0.81482718]]

 [[ 1.38218948 -0.95025527 -0.43193421]]]


In [22]:
scaler = StandardScaler()
# transform data
scaled = scaler.fit_transform(data)
print(scaled)

[[ 1.40843432  1.38218948]
 [-0.59360713 -0.95025527]
 [-0.81482718 -0.43193421]]
