In [15]:
import torch
import torchvision
import torchvision.transforms as transforms
import numpy as np
import matplotlib.pyplot as plt
torch.set_printoptions(linewidth=140)


train_set = torchvision.datasets.FashionMNIST(
    './FashionMNIST',
    train=True,
    download=True,
    transform=transforms.Compose([transforms.ToTensor()]) # converting ToTensor
)

In [4]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class NetWork_5(nn.Module):
    
    def __init__(self):
        super(NetWork_5, self).__init__()
        
        self.conv1 = nn.Conv2d(in_channels=1, out_channels=6, kernel_size=5)
        self.conv2 = nn.Conv2d(in_channels=6, out_channels=12, kernel_size=5)
   
        self.fc1 = nn.Linear(in_features=12*4*4, out_features=120)
        self.fc2 = nn.Linear(in_features=120, out_features=60)
        self.out = nn.Linear(in_features=60, out_features=10)
        
    def forward(self, t):
        
        t = F.relu(self.conv1(t))
        t = F.max_pool2d(t, kernel_size=2, stride=2) # will reduce the hieght and width our image
        
        t = F.relu(self.conv2(t))
        t = F.max_pool2d(t, kernel_size=2, stride=2)
        
        t = F.relu(self.fc1(t.reshape(-1, 12*4*4)))
        t = F.relu(self.fc2(t))
        t = self.out(t)
        
        return t

In [5]:
torch.set_grad_enabled(False)
netWork = NetWork_5()

sample_5 = next(iter(train_set)) ### will help you to get one data in a time
images, labels = sample_5
images.shape

torch.Size([1, 28, 28])

In [6]:
netWork.conv1.weight.shape
#### torch.Size([6, 1, 5, 5]) 
# 6 represents num of filters
# 1 represents the depth of each filter
# 5 and 5 represents the height and width of the filter
# all filters represent using a single tensor

torch.Size([6, 1, 5, 5])

In [7]:
images.unsqueeze(0).shape

torch.Size([1, 1, 28, 28])

In [8]:
#### prediction
pred = netWork(images.unsqueeze(0))
pred

tensor([[-0.0567,  0.1057,  0.0664,  0.0659, -0.1346, -0.0653,  0.0039, -0.0737, -0.1034,  0.0175]])

In [14]:
pred.argmax(dim=1)

tensor([1])

In [10]:
#### Compair with the real
pred.argmax(dim=1).eq(labels)

tensor([False])

 # Make prediction for set or batch of data


In [11]:
data_loader = torch.utils.data.DataLoader(train_set, batch_size=10)
batch_sample = next(iter(data_loader))
images2, labels2 = batch_sample
images2.shape

torch.Size([10, 1, 28, 28])

In [12]:
pred2 = netWork(images2)
pred2

tensor([[-0.0567,  0.1057,  0.0664,  0.0659, -0.1346, -0.0653,  0.0039, -0.0737, -0.1034,  0.0175],
        [-0.0600,  0.1004,  0.0707,  0.0765, -0.1297, -0.0660,  0.0091, -0.0739, -0.1021,  0.0187],
        [-0.0612,  0.1069,  0.0705,  0.0777, -0.1232, -0.0628, -0.0021, -0.0636, -0.1026,  0.0247],
        [-0.0595,  0.1072,  0.0716,  0.0764, -0.1264, -0.0664,  0.0017, -0.0675, -0.1046,  0.0211],
        [-0.0603,  0.1025,  0.0716,  0.0734, -0.1275, -0.0665,  0.0069, -0.0716, -0.0978,  0.0190],
        [-0.0622,  0.1035,  0.0705,  0.0727, -0.1351, -0.0626,  0.0033, -0.0744, -0.0984,  0.0194],
        [-0.0579,  0.1092,  0.0744,  0.0750, -0.1325, -0.0598,  0.0026, -0.0747, -0.0985,  0.0171],
        [-0.0667,  0.1035,  0.0658,  0.0692, -0.1296, -0.0653,  0.0043, -0.0673, -0.0977,  0.0229],
        [-0.0669,  0.1136,  0.0660,  0.0728, -0.1313, -0.0626, -0.0009, -0.0673, -0.1090,  0.0214],
        [-0.0607,  0.1072,  0.0679,  0.0728, -0.1357, -0.0659,  0.0018, -0.0739, -0.1002,  0.0184]])

# Compaire

In [13]:
pred2.argmax(dim=1).eq(labels2)

tensor([False, False, False, False, False, False, False, False, False, False])