In [16]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import style
from statistics import mean
from sklearn import linear_model, neighbors
import seaborn as sns

from sklearn.model_selection import train_test_split 


df = pd.read_csv('breast-cancer-wisconsin.data')
df.head()


1000025  5   1  1.1  1.2  2 1.3  3  1.4  1.5  2.1
0  1002945  5   4    4    5  7  10  3    2    1    2
1  1015425  3   1    1    1  2   2  3    1    1    2
2  1016277  6   8    8    1  3   4  3    7    1    2
3  1017023  4   1    1    3  2   1  3    1    1    2
4  1017122  8  10   10    8  7  10  9    7    1    4

In [17]:
df.rename(columns={
    '1000025': 'id',
    '5': 'Clump_Thickness',
    '1': 'Uniformity_of_Cell_Size',
    '1.1': 'Uniformity_of_Cell_shape',
    '1.2': 'Marginal_Adhesion',
    '2': 'Single_Epithelial_Cell_Size',
    '1.3': 'Bare_Nuclei',
    '3' : 'Bland_Chromatin',
    '1.4': 'Normal_Nucleoli',
    '1.5': 'Mitoses',
    '2.1': 'Class'
}, inplace=True)


In [18]:
df.head()

id  Clump_Thickness  Uniformity_of_Cell_Size  \
0  1002945                5                        4   
1  1015425                3                        1   
2  1016277                6                        8   
3  1017023                4                        1   
4  1017122                8                       10   

   Uniformity_of_Cell_shape  Marginal_Adhesion  Single_Epithelial_Cell_Size  \
0                         4                  5                            7   
1                         1                  1                            2   
2                         8                  1                            3   
3                         1                  3                            2   
4                        10                  8                            7   

  Bare_Nuclei  Bland_Chromatin  Normal_Nucleoli  Mitoses  Class  
0          10                3                2        1      2  
1           2                3                1        1      2  
2           4                3                7        1      2  
3           1                3                1        1      2  
4          10                9                7        1      4

# Data cleaning
#### 11. Class:                        (2 for benign, 4 for malignant)
#### df['Bare_Nuclei'].value_counts()  ---- you've 16('?') values

In [19]:
# we have 16 values
found_missing = df[df['Bare_Nuclei'] == '?']
# found_missing

In [20]:
# replace it with 0
df.replace('?', 0, inplace=True)
found_missing = df[df['Bare_Nuclei'] == '?']
found_missing

Empty DataFrame
Columns: [id, Clump_Thickness, Uniformity_of_Cell_Size, Uniformity_of_Cell_shape, Marginal_Adhesion, Single_Epithelial_Cell_Size, Bare_Nuclei, Bland_Chromatin, Normal_Nucleoli, Mitoses, Class]
Index: []

### Drop useless data --- like id

In [21]:
df.drop(['id'], axis=1, inplace=True)

In [22]:
df.head()

Clump_Thickness  Uniformity_of_Cell_Size  Uniformity_of_Cell_shape  \
0                5                        4                         4   
1                3                        1                         1   
2                6                        8                         8   
3                4                        1                         1   
4                8                       10                        10   

   Marginal_Adhesion  Single_Epithelial_Cell_Size Bare_Nuclei  \
0                  5                            7          10   
1                  1                            2           2   
2                  1                            3           4   
3                  3                            2           1   
4                  8                            7          10   

   Bland_Chromatin  Normal_Nucleoli  Mitoses  Class  
0                3                2        1      2  
1                3                1        1      2  
2                3                7        1      2  
3                3                1        1      2  
4                9                7        1      4

In [35]:
df['Class'].value_counts()

2    457
4    241
Name: Class, dtype: int64

# split - Train

# KNN

In [50]:
# Separate feature & target(label)
X = np.array(df.drop(columns=['Class'], axis=1))
Y = np.array(df['Class'])

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)



# X_train acc
model = neighbors.KNeighborsClassifier()
model.fit(X_train, Y_train)
trainPred = model.predict(X_train)
train_accur = accuracy_score(Y_train, trainPred)
print('Train_prediction >>> ',  train_accur)

model = neighbors.KNeighborsClassifier()
model.fit(X_test, Y_test)
testPred = model.predict(X_test)
test_accur = accuracy_score(Y_test, testPred)

print(' Test_prediction >>> ', test_accur)

Train_prediction >>>  0.9767025089605734
 Test_prediction >>>  0.9642857142857143


# Confusion_matrix

In [62]:
confusion_matrix(Y_train, svcpred)

xtrain = confusion_matrix(Y_train, trainPred)
xtest = confusion_matrix(Y_test, testPred)
xtrain, xtest

(array([[358,   8],
        [  5, 187]]),
 array([[90,  1],
        [ 4, 45]]))

# SVM

In [72]:
# svc
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix

svmModel = SVC()
svmModel.fit(X_train, Y_train)

# xTrian
svcpred = svmModel.predict(X_train)
svcAccu = accuracy_score(Y_train, svcpred)
print(svcAccu)

# xTest
svcXtestpred = svmModel.predict(X_test)
svcXtestAccu = accuracy_score(Y_test, svcXtestpred)
print(svcXtestAccu)

# accuracy
confusion_matrix(Y_train, svcpred), confusion_matrix(Y_test, svcXtestpred)


0.9767025089605734
0.9714285714285714


(array([[356,  10],
        [  3, 189]]),
 array([[90,  1],
        [ 3, 46]]))

# Now we can predict 

In [24]:
given_input1 = np.array([8,10,10,8,7,10,9,7,1]).reshape(1, -1) # class 4
pred_resu1 = model.predict(given_input1)
print(pred_resu1)

[4]


In [10]:
given_input2 = np.array([4,2,1,1,1,2,3,2,1]).reshape(1, -1)    # class 2
pred_resu2 = model.predict(given_input2)
print(pred_resu2)

[2]


# reshape(1, -1) ->>> 1 is the number of array -1 ?

In [11]:
given_input3 = np.array([ [4,2,1,1,1,2,3,2,1], [4,2,1,1,1,2,3,2,1] ]).reshape(2, -1)    # class 2
pred_resu3 = model.predict(given_input3)
print(pred_resu3)

[2 2]


# if you have more arrays make it dynamic by len(arrLen)

In [12]:
given_input4 = np.array([ [4,3,10,4,3,2,3,2,4], [8,10,10,8,7,10,9,7,1] ])
given_input4 = given_input4.reshape(len(given_input4), -1) 
pred_resu4 = model.predict(given_input4)
print(pred_resu4)

[2 4]


####  ValueError: Expected 2D array, got 1D array instead:
####  array=[4 2 1 1 1 2 3 2 1].
####  Reshape your data either using array.reshape(-1, 1) if your data has a single feature 
####  or array.reshape(1, -1) if it contains a single sample (one array)

# Euclidean-Distance --->>>> the distance b/n to coordinates on the graph

In [73]:
from math import sqrt

p1 = [1, 3]
p2 = [2, 5]

eucDis = sqrt( (p1[0] - p2[0])**2 + (p1[1] - p2[1])**2 )
print(eucDis)

2.23606797749979
