In [1]:
import torch

In [14]:
a = torch.arange(9)
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
for i in a:
    print(i.item())

0
1
2
3
4
5
6
7
8


In [16]:
a.shape[0], a.size(0)

(9, 9)

# Reshape function

In [18]:
a_reshaped = torch.reshape(a, (3, 3))
a_reshaped # the size will be (3, 3)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

# Flatten Tensor

In [24]:
b = torch.tensor([[4, 6], [2, 7]])
b_flattened = torch.reshape(b, (-1,))
b_flattened

tensor([4, 6, 2, 7])

# Squeeze

In [38]:
x = torch.zeros(1,2,1,2,1)
print(x)

tensor([[[[[0.],
           [0.]]],


         [[[0.],
           [0.]]]]])


In [40]:
squeezed_x = torch.squeeze(x) # will drop the tensor whose inputs are 1 dimensions 
squeezed_x 

tensor([[0., 0.],
        [0., 0.]])

# adding two tensor with different data types

In [48]:
t1 = torch.tensor([1,2,3])
t2 = torch.tensor([1.,2.,3.])
t1 + t2

tensor([2., 4., 6.])

In [46]:
t1.dtype, t2.dtype


(torch.int64, torch.float32)

In [50]:
import numpy as np

data = np.array([1, 2, 3])
type(data)

numpy.ndarray

In [56]:
res1 = torch.Tensor(data)
res1.dtype

torch.float32

In [57]:
res2 = torch.tensor(data)
res2.dtype

torch.int64

# Zeros

In [58]:
torch.zeros(2, 2)

tensor([[0., 0.],
        [0., 0.]])

In [59]:
torch.ones(2, 2)

tensor([[1., 1.],
        [1., 1.]])

In [60]:
torch.rand(2, 2)

tensor([[0.5644, 0.9444],
        [0.6894, 0.7165]])

# Ones

In [113]:
sample_one = torch.ones(1, 1, 28, 28)
sample_one.shape

torch.Size([1, 1, 28, 28])

In [ ]:
# # simple Hang man
# import random

# words = ['God', 'Gduod']

# random_word = [letter for letter in random.choice(words)]
# print(random_word)

# decrypted = ['-' for letter in random_word]
# print(" ".join(decrypted))

# i = 0

# not_found = True

# while i < len(random_word):
#     user_guess = input('Enter your guess letter below ...')
#     for ix in range(len(random_word)):
#         if random_word[ix] == user_guess:
#             decrypted[ix] = user_guess
#             print(" ".join(decrypted))
#             i += 1
#     if user_guess not in random_word:
#         print(f'{user_guess} not founded.......')

#     if decrypted == random_word:
#         print('Won ... . ')


# To contact tensors use the stack

In [65]:
data_1 = torch.tensor([
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1]
])

data_2 = torch.tensor([
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2]
])

data_3 = torch.tensor([
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3]
])

allDatas = torch.stack((data_1, data_2, data_3))
allDatas.shape
# torch.Size([3, 4, 4]) ---> 3 is the batch_size, 4,4 tells us the height and width

torch.Size([3, 4, 4])

In [66]:
allDatas

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2]],

        [[3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3]]])

In [67]:
v = torch.tensor([1,2])
v + 2

tensor([3, 4])

# !!!!!  dim=1 dim=0 during sum

In [71]:
data_4 = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [4,4,4,4]
])

In [72]:
data_4.sum(dim=0)

tensor([7, 7, 7, 7])

In [73]:
data_4.sum(dim=1)

tensor([ 4,  8, 16])

# Linear layer

In [106]:
in_featuresOne = torch.tensor([1,2,3,4])

In [107]:
weight_matrix = torch.tensor([
    [1,2,3,4],
    [2,3,4,5],
    [3,4,5,6]
])

In [110]:
weight_matrix.matmul(in_featuresOne) # we are Implementing the matrix multiplication operation 

tensor([30, 40, 50])

# PyTorch Linear Layer

In [111]:
import torch.nn as nn
fc = nn.Linear(in_features=4, out_features=3)
fc

Linear(in_features=4, out_features=3, bias=True)

In [13]:
for i in range(5):
    print("*" * i)


*
**
***
****


In [42]:
import random
players_name = ['Messi', 'Chrstiano', 'Seim', 'Tesfit']

name_to_gues = random.choice(players_name)

for alp in name_to_gues:
    print(' _ ', end='')
    

 _  _  _  _  _  _ 

In [ ]:
_ _ _ _ _

In [ ]:
class Players():
    
    def __init__(self, name, age, hei):
        self.name = name
        self.height = height
        
    def show_name():
        name = 
        
        
players('Siem', 23, 170)

In [ ]:
import random

words = ['Seim', 'Tesfit', 'Royal']


random_word = [letter for letter in random.choice(words)]
print(random_word)

hide  = [" _ " for letter in random_word] 
print(hide)


# then check if the user's letter is in the random word



while True:
    # first ask user
    user_input = input('Enter a letter to start the game...')
    
    
    for index in range(len(random_word)):
        if user_input == random_word[index]:
           # if user gues is correct Encrypt 
            hide[index] = user_input
            print (" ".join(hide))
        
        if hide == random_word:
            print('You got all the letters, Congrats you 🏅')
        
        if user_input not in random_word:
            print('The letter u have entered is not in the game')


['S', 'e', 'i', 'm']
[' _ ', ' _ ', ' _ ', ' _ ']
