### Loss function

##### To find the best fit line U need to calculate the difference b/n 
***the true(the true dots) value and estimate-dots(predicted-value. distance from the line to the axis) ***
##### use loss function for that

# Y^ -> y-hot means the points of the best fit line -- formula is y = mx+c

In [55]:
import pandas as pd
import seaborn as sns
import numpy as np
from sklearn.model_selection import train_test_split

# Single linear regression
##### Slope means what is the change value of y if the x value changes by any num

In [56]:
# find the value of m and c  based the formula y=mx+c

# y = mx + c

# y = y-value
# x = x-value
# m = slope
# c = intercept

# let's take two data-point
p1 = (2, 7)
p2 = (3, 9)

# first find the slope
# m = dy/dx we can use this as well d-represents differecnc

m = (y2-y1 / x2-x1)
m = 9-7/3-2
m = 2  

# now find c by taking another datapoint p1 = (3, 9)
# c = y - mx
# c = 9 - 2(3)
# c = 3

In [57]:
# Linear equation  Y = mx + c

# Single Linear Regression   Y' = B0 + BX

# Multiple  Linear Regression Y' = B0 + B1X1 + B2X2 + B3X1X2

In [58]:
array_2d = np.zeros((2, 3))
print(array_2d)

[[0. 0. 0.]
 [0. 0. 0.]]


In [59]:
import numpy as np
# for 1-DIMENSIONAL ARRAYS the np.dot computes the vector(array) dot product
# So The output is a single scalar value

c = np.array([3, 4, 5])
q = [7, 8, 9]
c.dot(q)

# or this way
a = [3, 4, 5]     
b = [7, 8, 9]
np.dot(a, b)      # ------> 3*7 + 4*8 + 5*9 = 98
output = 98


# IF ONE OF THE INPUTS IS A SCALAR, NP.DOT PERFORMS SCALAR MULTIPLICATION
r = 2
k = [7, 8, 9]
np.dot(r,k)  
output = [14, 16, 18]


# Let’s say that you have two 2D arrays,.
v = [[3, 4, 5], [6, 7, 8]]
z = [[10, 11], [12, 13], [14, 15]]
np.dot(v,z)
output = [ [148, 160], [256, 277] ]

In [61]:
class Logistic_Regression:
    
    def __init__(self, lr=0.0001, no_itr=1000):
        self.lr = lr
        self.no_itr = no_itr
        self.weighst = None
        self.bias = None
        
    def fit(self, X, y):
        n_samples, n_features = X.shape
        self.weights = np.zeros(n_features)
        self.bias = 0
        
        # ** initiate the weight and base **
        # y = wX + b
        # w = w - α*dw  -> we are useing - b/c we are going down and α(alpha) shows the learning rate (how far we go down)
        # b = b - α*db
        # db = formula
        # dw = formula
        
        
        # gradient descent
        for i in range(self.no_itr):
            #y           =        wX               +      b    
            linear_model = np.dot(X, self.weights) + self.bias
            y_predi = self.sigmoidFunc(linear_model) # converts the -ve to +ve and create the S-curved line(b/n 0-1)
            
            # update the w and b  ======> w = w - α*dw and  # b = b - α*db
            
            dw = (1/n_samples) * np.dot(X.T, (y_predi - y))
            db = (1/n_samples) * np.sum(y_predi - y)
            
            self.weights = self.weights - self.lr*dw
            self.bias = self.bias - self.lr*db
            
                
    def predict(self, x):
        #y = wX + b
        linear_model = np.dot(x, self.weights) + self.bias
        y_predi = self.sigmoidFunc(linear_model)
        predicted_y_cls = [1 if i > 0.5 else 0 for i in y_predi]
        return predicted_y_cls
    
    def accuracy(self, real_ytest, predi_y):
        #_y = real_ytest.reshape(-1, 1)
        # the booli will return [[True, False, False, True, True, False]] then it will add only the True values
        # np.sum([[True, False, False, True, True, False]])
        booli = (predi_y == real_ytest)
        acc = np.sum(booli)/len(real_ytest)
        return acc



    def sigmoidFunc(self, x):
        return (1/1+np.exp(-x))
        

# This simple and straightforward equation works for linear regression because linear regression uses a simple linear equation: (Y= A+BX).
# But logistic regression uses a sigmoid function which is not linear.

# Test it

In [62]:
# now we can test it by feeding dataSet
from sklearn.datasets import load_breast_cancer
breast_cancer = load_breast_cancer()

# split
X = breast_cancer['data']
y = breast_cancer['target']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1234)


# train the model
my_model = Logistic_Regression()
my_model.fit(X_train, y_train)
predi_result = my_model.predict(X_test)
print(predi_result)


# accu
my_model.accuracy(y_test, predi_result)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


<ipython-input-61-6be4b7015f2e>:68: RuntimeWarning: overflow encountered in exp
  return (1/1+np.exp(-x))


0.38596491228070173

In [ ]:
r = np.sum((np.array([8,4]) - np.array([6, 6]))) 
r

In [ ]:
dw = (1/m)*(y_hat — y).X
db = (1/m)*(y_hat — y)

In [83]:
def gradients(X, y, y_hat):
    
    # X --> Input.
    # y --> true/target value.
    # y_hat --> hypothesis/predictions.
    # w --> weights (parameter).
    # b --> bias (parameter).
    
    # m-> number of training examples.
    m = X.shape[0]
    
    # Gradient of loss w.r.t weights.
    dw = (1/m)*np.dot(X.T, (y_hat - y))
    
    # Gradient of loss w.r.t bias.
    db = (1/m)*np.sum((y_hat - y)) 
    
    return dw, db

# gradients(X, y, np.array([6, 8]))

569 30
569
569


# Resahpe

In [88]:
def reshape(X, y):
    # n_fe-> number of training examples
    # n_sa-> number of features 
    n_fe, n_sa = X.shape
    print(n_fe, n_sa)
    print(len(y))
    #print(y.reshape(n_fe, 1))
    print(len(y.reshape(n_fe, 1))) # meaning we're converting it from [0,1,1,0,0] to [[0],[1],[1],[0],[0]]
    
reshape(X, y)

569 30
569
569


In [ ]:
#Now, we want to know how our hypothesis(y_hat) is going to make predictions of whether y=1 or y=0.
y=1 when y_hat ≥ 0.5
y=0 when y_hat < 0.5

# meaning
y=1 when w.X + b ≥ 0
y=0 when w.X + b < 0

In [72]:
# Reshape
b = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
b.reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])