In [35]:
import numpy as np

# by optimizing the weight we minimize the loss error
# our weight get updats cuz during the backward the w be multiplied by the learning rate !!!

In [30]:
bias = 0.5
weights = np.array([0.4, 0.2, 0.6])
lr = 0.01
target = np.array([0,1,0,1])
inputData = np.array(([0.1,0.5,0.2], [0.2,0.3,0.1], [0.7,0.4,0.2], [0.1,0.4,0.3]))


In [31]:
        # Activation Function
def sigmoid(w_sum):
    return 1/(1+np.exp(-w_sum))

# Get Model Output
def get_prediction(features, weights, bias):
    return sigmoid(np.dot(features, weights) + bias)



In [32]:
def gradient_descent(w, b, target, predData, inputData, lr):
    boxNewWeights = []
    
    new_bias = b + lr * (target - predData)
    
    for x,w in zip(inputData, w):
        print(x)
        new_w = w + lr*(target - predData) 
        print(new_w, predData)
        new_w = np.multiply(new_w, x)
                        
        boxNewWeights.append(new_w)
        print(type(new_w), type(x))
        
    return boxNewWeights, new_bias


grad_des = gradient_descent(weights, bias, target, get_prediction(inputData, weights, bias), inputData, lr)
# print(grad_des)
        


[0.1 0.5 0.2]
[0.39318646 0.40331812 0.39272892 0.40310026] [0.68135373 0.66818777 0.72710822 0.68997448]


ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [33]:
X = np.arange(8)
y = np.arange(2).reshape(1, 2)
X

array([0, 1, 2, 3, 4, 5, 6, 7])