# Logistic_Regration with tensor

In [12]:
# 1 desigh your model
# 2 construct loss and optimizer
# 3 trainig loop
    # compute pred : loss
    # gradients : backward pass
    # update weights : backward.step()

In [13]:
import torch
import torch.nn as nn
import numpy as np
from sklearn import datasets
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler

In [14]:
# get the data
myData = datasets.load_breast_cancer()
X = myData['data']
y = myData['target']

# split the col and row
n_samples, n_features = X.shape
n_samples, n_features


(569, 30)

In [15]:

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.02, random_state=1234)
X_train.shape, y_train.shape


((557, 30), (557,))

# Scaleing

In [16]:
scale = StandardScaler()
X_train = scale.fit_transform(X_train)
X_test = scale.transform(X_test)

type(X_test)

numpy.ndarray

In [17]:
y_test

array([1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1])

# Convert to Torch or tensor

In [18]:
X_train = torch.from_numpy(X_train.astype(np.float32))
X_test  = torch.from_numpy(X_test.astype(np.float32))
y_train = torch.from_numpy(y_train.astype(np.float32))
y_test  = torch.from_numpy(y_test.astype(np.float32))
y_test

tensor([1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0., 1.])

# Resahpe the y_

In [19]:
# NOT quite understand why i am doing this........ >>> i think b/c we always need flattend target
# view and reshape are same
print(y_test)

y_train = y_train.view(y_train.shape[0], 1)
y_test = y_test.view(y_test.shape[0], 1)

print(y_test) 

tensor([1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0., 1.])
tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.]])


# 1. Build model 

In [20]:
class Logistic_Regresion(nn.Module):  
    def __init__(self, input_features):
        super(Logistic_Regresion, self).__init__()
        self.linear = nn.Linear(in_features=input_features, out_features=1)
        
    def forward(self, x):
        y_pred = torch.sigmoid(self.linear(x))
        return y_pred
    
model = Logistic_Regresion(n_features)

# 2 construct loss and optimizer

In [21]:
loss_func = nn.BCELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

# 3 trainig loop

In [22]:
                                # compute pred : loss
                                # gradients : backward pass
                                # update weights : backward.step
for epoch in range(100):
    y_predicted = model(X_train)
    loss = loss_func(y_predicted, y_train)
    loss.backward()
    
    optimizer.step()
    optimizer.zero_grad()
    
    if (epoch+1) % 10 == 0:
        print(f'epoch: {epoch+1}, loss = {loss.item():.4f}')

with torch.no_grad():
    y_pred = model(X_test)
    print(y_pred)
    acc = accuracy_score(y_pred.round(), y_test) #### becare full with the [[type shape and others.....]]
    print(f"Accuracy:>>> {acc}")

epoch: 10, loss = 0.5060
epoch: 20, loss = 0.4324
epoch: 30, loss = 0.3827
epoch: 40, loss = 0.3467
epoch: 50, loss = 0.3194
epoch: 60, loss = 0.2980
epoch: 70, loss = 0.2806
epoch: 80, loss = 0.2661
epoch: 90, loss = 0.2539
epoch: 100, loss = 0.2434
tensor([[0.7337],
        [0.9467],
        [0.4304],
        [0.8757],
        [0.7959],
        [0.6161],
        [0.4400],
        [0.9206],
        [0.0355],
        [0.0717],
        [0.0668],
        [0.6350]])
Accuracy:>>> 0.9166666666666666
